<?php

return [

    'banklist' => [
        '0' => 'Select your bank',
        '1' => 'Affin Bank Berhad',
        '2' => 'Alliance Bank Malaysia Berhad',
        '3' => 'AmBank (M) Berhad',
        '4' => 'BNP Paribas Malaysia Berhad',
        '5' => 'Bangkok Bank Berhad',
        '6' => 'Bank of America Malaysia Berhad',
        '7' => 'Bank of China (Malaysia) Berhad',
        '8' => 'Bank of Tokyo-Mitsubishi UFJ (Malaysia) Berhad',
        '9' => 'CIMB Bank Berhad',
        '10' => 'Citibank Berhad',
        '11' => 'Deutsche Bank (Malaysia) Berhad',
        '12' => 'HSBC Bank Malaysia Berhad',
        '13' => 'Hong Leong Bank Berhad',
        '14' => 'India International Bank (Malaysia) Berhad',
        '15' => 'Industrial and Commercial Bank of China (Malaysia) Berhad',
        '16' => 'J.P. Morgan Chase Bank Berhad',
        '17' => 'Malayan Banking Berhad',
        '18' => 'Mizuho Bank (Malaysia) Berhad',
        '19' => 'National Bank of Abu Dhabi Malaysia Berhad',
        '20' => 'OCBC Bank (Malaysia) Berhad',
        '21' => 'Public Bank Berhad',
        '22' => 'RHB Bank Berhad',
        '23' => 'Standard Chartered Bank Malaysia Berhad',
        '24' => 'Sumitomo Mitsui Banking Corporation Malaysia Berhad',
        '25' => 'The Bank of Nova Scotia Berhad',
        '26' => 'The Royal Bank of Scotland Berhad',
        '27' => 'United Overseas Bank (Malaysia) Bhd.',
        '28' => 'Affin Islamic Bank Berhad',
        '29' => 'Al Rajhi Banking & Investment Corporation (Malaysia) Berhad',
        '30' => 'Alliance Islamic Bank Berhad',
        '31' => 'AmBank Islamic Berhad',
        '32' => 'Asian Finance Bank Berhad',
        '33' => 'Bank Islam Malaysia Berhad',
        '34' => 'Bank Muamalat Malaysia Berhad',
        '35' => 'CIMB Islamic Bank Berhad',
        '36' => 'HSBC Amanah Malaysia Berhad',
        '37' => 'Hong Leong Islamic Bank Berhad',
        '38' => 'Kuwait Finance House (Malaysia) Berhad',
        '39' => 'Maybank Islamic Berhad',
        '40' => 'OCBC Al-Amin Bank Berhad',
        '41' => 'Public Islamic Bank Berhad',
        '42' => 'RHB Islamic Bank Berhad',
        '43' => 'Standard Chartered Saadiq Berhad',
        '44' => 'Affin Hwang Investment Bank Berhad',
        '45' => 'Alliance Investment Bank Berhad',
        '46' => 'AmInvestment Bank Berhad',
        '47' => 'CIMB Investment Bank Berhad',
        '48' => 'Hong Leong Investment Bank Berhad',
        '49' => 'KAF Investment Bank Berhad',
        '50' => 'Kenanga Investment Bank Berhad',
        '51' => 'MIMB Investment Bank Berhad',
        '52' => 'Maybank Investment Bank Berhad',
        '53' => 'Public Investment Bank Berhad',
        '54' => 'RHB Investment Bank Berhad',
        '55' => 'Al Rajhi Banking & Investment Corporation',
        '56' => 'Deutsche Bank Aktiengesellschaft',
        '57' => '"PT Bank Muamalat Indonesia, Tbk"',
    ]

];
